const questions = [
    "Epicką skrzynke tworzy się z bloków diamentu i bloków złota?",
    "Szansa na drop diamentu i szmaragdu z kamienia jest taka sama?",
    "Koszt komendy /farma zbierz to 1 500$",
    "Ghast posiada 9 macek na jego brzuchu?",
    "Aby wydobyć blok diamentu, trzeba mieć co najmniej żelazny kilof?",
    "Czy da się rozlać wodę w endzie?",
    "Czy koszt kupna siekiery u NPC na /warp tartak to 100$?",
    "Czy w minecraft jest 15 kolorów betonu?",
    "Czy na działce można zablokować maksymalnie 20 osób?",
    "Czy w minecraft wyróżniamy 8 faz księżyca?",
    "Czy targ można wyróżnić maksymalnie + 6dni?",
    "Czy koszt przeniesienia targu to 15k?",
    "Czy istnieje więcej niż jedna działka o takich samych wymiarach?",
    "Czy zawsze w fortecy występuje pokój z brodawkami?",
    "Pełny set robi się z 24 diamentów?",
    "Czy działka normalna ma wymiary 33x33?",
    "Czy łancuch można wydobyć kamiennym kilofem?",
    "Po zniszczeniu rudy lazurytu wypada maksymalnie 4 sztuki lazurytu?",
    "Czy w minecraft są pszczoły?",
    "Czy enderman jest mobem neutralnym?",
    "Czy na serwerze jest 10 ogrodzeń działki do wybrania?",
    "Czy chunki mają wymiary 16x16x384?",
    "Czy pajęczyne robi się z 9 nici",
    "Czy istnieje szansa, że witherowy szkielet upuści drewniany miecz?",
    "Aby wydobyć blok diamentu, możemy użyć złotego kilofa?",
    "Czy chmury w minecraft zawsze poruszają się w kierunku wschodnim?",
    "Czy pradawne zgliszcza można wydobyć dopiero z 3lvl pracy kowala?",
    "Aby zrobić książkę z piórem, potrzebujemy książki i pióra",
    "Czy na kowadło działa grawitacja?",
    "Czy w endzie występuje 1 biom?",
    "Czy słońce w minecraft wschodzi na zachodzie i zachodzi na wschodzie?",
    "Czy dzień w minecraft trwa 24 minuty?",
    "Czy prowiant robi się z 4 różnych przedmiotów?",
    "Czy otrzymasz legendarną skrzynke za wbicie 21 globalnego poziomu pracy?",
    "Czy magiczną latarnie można wydobyć łapka?",
    "Czy za zdobycie 30 poziomu globalnego otrzymamy żeton/skrzynke lege/skrzynke mityk?",
    "Czy dzień w minecraft trwa 10 minut?",
    "Czy blok siana postawiony pod ogniskiem da więcej dymu?",
    "Czy minimalny Y regenerowania działki to 10?",
    "Czy platforma, na którą jesteśmy teleportowani po wejściu do endu jest wykonana z obsydianu?",
    "Czy zbrojmistrz potrzebuje kamienia szlifierskiego jako swoje stanowisko pracy?",
    "Czy jasnogłaz generuje 10 poziom światła?",
    "Czy można stworzyć magmowy krem?",
    "Czy na /warp receptury jest ich 21?",
    "Czy dostępnych kolorów wełny jest 10?",
    "Czy można barwić łóżka na wersji 1.12",
    "Czy jest ponad 36 rodzajów strzał w minecraft?",
    "Czy najwolniejszy mob w grze to leniwa panda?",
    "Czy papugi można rozmnożyć ciastkami?",
    "Czy wyróżniamy 6 różnych poziomów u osadników?",
    "Czy Nadzorca ma 500 punktów zdrowia?",
    "Czy obecna edycja rozpoczęła się 6 lipca?",
    "Czy łancuch można wydobyć jakimkolwiek kilofem?",
    "Czy do stworzenia magnetytu potrzebna jest sztabka netherytu",
    "Czy eteryczny ogień zadaje więcej obrażeń od zwykłego ognia?",
    "Czy lód i śnieg topnieją, gdy poziom światła wynosi 11?",
    "Czy można zneleźć zakopany skarb niekorzystając z mapy skarbów?",
    "Czy w minecraft wyróżniamy 9 faz księżyca?",
    "Czy w pradawnym mieście respią się 3 rodzaje mobów?",
    "Czy chmury w minecraft zawsze poruszają się w kierunku zachodnim?",
    "Czy jest szansa, że rybik cukrowy upuści po śmierci coś oprócz punktów doświadczenia?",
    "Czy błonami fantoma można naprawić elytre?",
    "Czy na kowadło nie działa grawitacja?",
    "Czy oswojonego wilka można nakarmić zgniłym mięsem?",
    "Czy wielkie grzyby naturalnie generują się w puszczach?",
    "Czy w minecraft istnieje 8 rodzajów drzew?",
    "Czy istnieje ponad 15 bloków, które ulegają grawitacji?",
    "Czy targ można wyróżnić maksymalnie o 7dni?",
    "Czy koszt przeniesienia targu to 20k?",
    "Po zabiciu kury przy użyciu miecza z zaklęciem Grabież może wypaść do 4 sztuk surowego kurczaka",
    "Płomyki odradzają się wyłącznie w netherowych twierdzach.",
    "Pszczoły zbierają pyłek z kwiatów do chwili, gdy tekstura owada posiada na sobie pył.",
    "Karmienie delfinów dorszem spowoduje, że popłyną one do najbliższych podwodnych ruin lub wraku statku.",
    "Posuch zachowuje się tak samo jak zwykły zombie, jednak nie płonie w świetle słonecznym.",
    "Czy w grze wither był kiedykolwiek czerwony?",
    "Endermany są odporne trójzęby?",
    "Wędrowni handlarze odradzają się losowo na całym świecie",
    "Po zniszczeniu rudy lazurytu wypada 4–6 sztuk lazurytu",
    "Zbity lód jest solidnym blokiem",
    "Gdy aksolotl otrzyma duże obrażenia, może udawać martwego.",
    "Ghast posiada 8 macek na jego brzuchu?",
    "Po śmierci z żelaznego golema może wypaść mak?",
    "Pulpit trzymający książkę wyemituje sygnał redstone po przełożeniu strony",
    "Krosno może służyć także jako blok stacji roboczej dla pasterza.",
    "Beczka może pomieścić tyle samo przedmiotów co pojedyncza skrzynka",
    "Statywy alchemiczne emitują światło o poziomie 2",
    "Aby wydobyć blok diamentu, trzeba mieć co najmniej kamienny kilof.",
    "Siła sygnału wysyłanego przez detektor światła dziennego zależy od pory dnia",
    "Czy istnieją 2 typy działek o takich samych wymiarach?",
    "Aktualnie posiadamy na serwerze więcej niż 5 ModChatów?",
    "Zdobycie główki z czarnego szkieleta staje się możliwe dopiero po wbiciu 10. poziomu pracy Łowcy",
    "Regeneracja działki to możliwość zamienienia powietrza w kamień",
    "Mityczną skrzynkę zdobędziesz uzyskując 20 poziom dowolnej pracy",
    "Czy lunar client jest dozwolony na naszym serwerze?",
    "Podręczny piec hutniczy craftuje się z 3 bloków węgla i pieca",
    "Jazda w wagoniku nie zalicza się do omijana systemu AntyAFK",
    "Wieśniaki da się mieć jedynie na mapie surowcowej",
    "Stojaki na zbroję(stojące) nie mogą być zniszczone kaktusem.",
    "Jasnogłaz świeci światłem, na poziomie 5",
    "Szyba nie może zostać postawiona poziomo.",
    "Aby zrobić książkę z piórem, potrzebujemy książki, pióra i atramentu.",
    "Czy maksymalny poziom zregenerowania działki to 60?",
    "Czy żaby występują w 3 wariantach?",
    "Czy istnieją moby, które tracą życie podczas pobytu na bloku piasku dusz?",
    "Czy Aksolotle można przyczepić do smyczy?",
    "Czy przewodnia może atakować wrogie moby?",
    "Czy mob otuszek służy głównie do zbierania bloków?",
    "Czy osadnicy posiadają harmonogram dnia?",
    "Czy jest szansa na zamianę osadnika w wiedźmę?",
    "Czy kaktus może zniszczyć sztabkę netherytu?",
    "Czy maksymalna liczba wygenerowanych pradawnych zgliszcz przypadająca na chunk to 5?",
    "Czy forteca netheru generuje się naturalnie tylko w netherze?",
    "Czy pokój z brodawkami w fortecy w netherze zawsze się generuje?",
    "Czy płaczący obsydian można wydobyć żelaznym kilofem z wydajnością V?",
    "Czy leśny dwór generuje się tylko w puszczy?",
    "Czy istnieje szansa na odrodzenie innego moba niż nadzorca w pradawnym mieście?",
    "Czy po zniszczeniu sculku dostaniemy punkty doświadczenia?",
    "Czy istnieje mob, którego nie spowalniają pajęczyny?",
    "Czy nożyce niszczą pajęczynę tak szybko jak miecz?",
    "Gładki kamień to jedyny blok, który posiada własny wariant półbloku, ale nie posiada wariantu schodów?",
    "Czy szyba wypełnia pełen obszar jednego okienka w ekwipunku?",
    "Czy bałwany zamrażają wodę, po której chodzą?",
    "Czy istnieją ponad 23 biomy w minecraft?",
    "Czy kompostownik służy do tworzenia mączki kostnej?",
    "Czy istnieje szansa na znalezienie szmaragdu w igloo?",
    "Czy po przepaleniu żelaznych narzędzi otrzymamy bryłke żelaza?",
    "Czy świat w minecraft jest generowany metodą generowania proceduralnego?",
    "Czy istnieje ponad biliard różnych możliwych seedów do wygenerowania?",
    "Czy w minecraft istnieją strefy czasowe jak w normalnym świecie?",
    "Czy maksymalny poziom światła to 15?",
    "Czy słońce w minecraft wschodzi na wschodzie i zachodzi na zachodzie?",
    "Czy każda mapa(przedmiot) w minecraft ma tylko 2 parametry",
    "Czy noc w minecraft trwa 7 minut?",
    "Czy wioski naturalnie generują się tylko na 5 biomach?",
    "Czy w minecraft jest szansa na wygenerowanie opuszczonej wioski?",
    "Czy zabicie golema w wiosce odejmuje nam punkty reputacji w niej?",
    "Czy kamień szlifierski ma więcej niż jedno zastosowanie?",
    "Czy przecinarki generują się naturalnie w minecraft?",
    "Czy wędzarka może zostać przesunięta tłokiem?",
    "Czy wrzucenie placka dyniowego do kompostownika zawsze doda jeden poziom zapełnienia?",
    "Czy istnieją bloki, które mogą być bytami?",
    "Czy grawitacja działa tak samo na każdy byt?",
    "Czy minecraft to gra typu sandbox?",
    "Czy generowane portalu w netherze liczą 14 bloków obsydianu?",
    "Czy woda może zniszczyć słupek endu?",
    "Czy chunki mają wymiary 24x24x384?",
    "Czy do uzyskania maksymalnego wzmocnienia magicznej latarni potrzeba 128 bloków w platformie?",
    "Czy wither jest jedynym agresywnym mobem, którego może stworzyć gracz?",
    "Czy broń z zaklęciem pogromca nieumarłych pozwoli nam efektywniej zabić withera?",
    "Czy wither ma więcej życia od smoka endu?",
    "Czy trzcina może mieć 4 bloki wysokości?",
    "Czy na lame można nałożyć dywan?",
    "Czy lama to jedyny mob, od którego gracz może zginąć w trybie pokojowym?",
    "Czy leniwa panda jest najwolniejszym mobem w grze?",
    "Czy w trybie survival, trzeba stać 4 sekundy w portalu do netheru, aby zadziałał?",
    "Czy jest możliwość uruchomienia portalu do netheru z lawą w jego środku?",
    "Czy w netherze występuje cykl dnia i nocy?",
    "Czy większość stworzeń, które można spotkać w netherze są wrogo nastawione?",
    "Czy w netherze można postawić mokrą gąbke?",
    "Czy w netherze postawione liście wyglądają inaczej?",
    "Czy jest możliwe zniszczenie spiczastego nacieku jedynm uderzeniem?",
    "Czy w netherze morza lawy można spotkać na y = 21?",
    "Czy w zwykłym minecraft jedyną opcją, dzięki której wydostaniemy się z endu jest zabicie smoka",
    "Czy w endzie naturalnie występują tylko 2 rodzaje mobów, nie licząc smoka?",
    "Czy w endzie występuje tylko 5 biomów?",
    "Czy skała macierzysta naturalnie występuje w endzie?",
    "Czy da się zniszczyć wagonik łukiem?",
    "Jungla byla wprowadzona w wersji 1.8.1 beta?",
    "Pełny set robi się z 25 sztabek diamentów?",
    "Czy w minecraft istnieją niewiwdzialne bloki?",
    "Czy TNT niszczy lawe?",
    "Czy deszcz napełni kocioł?",
    "Czy szkielet widzi gracza przez kraty?",
    "Czy skrzynia pułapka trzymana w ręcę wygląda jak zwykła?",
    "Czy portal do nether'u emituje światło?",
    "Czy ciasto można użyć tylko 5 razy?",
    "Czy tabliczka może się spalić?",
    "Czy młode oceloty potrafią pływać?",
    "Czy moby naturalnie unikają wchodzenia na tory?",
    "Czy mooshroom daję zupę grzybową po użyciu na niej pustej miski?",
    "Czy twarda ziemia generuje się tylko na biomie mesa i sawanna?",
    "Czy w endzie występują zjawiska pogodowe?",
    "Czy można jeździć na delfinach?",
    "Czy enderman jest mobem agresywnym?",
    "Czy w świecie kresu lawa płynie szybciej?",
    "Czy fantomy boją się kotów?",
    "Czy walutą handlu z osadnikami są kartki papieru?",
    "Czy działka Premium v1 ma wymiary 50x50?",
    "Czy SVIP może latać na /warp s (/fly)?",
    "Czy noc w minecraft trwa 10 minut?",
    "Czy w Minecraft są osy?",
    "Czy slime jest przyjaznym mobem?",
    "Czy w wersji 1.20 został dodany dzbanek?",
    "Czy endermit jest mobem agresywnym?",
    "Czy w netherze działają kompasy?",
    "Czy kocioł to niezbędne narzędzie alchemiczne?",
    "Czy istnieje szansa, że witherowy szkielet upuści złoty miecz?",
    "Czy po zabiciu osadnika otrzymamy punkty doświadczenia?",
    "Czy da się usunąć blok obsydianu z portalu wygenerowanego w netherze, tak aby portal dalej działał?",
    "Czy Aksolotle mogą być agresywne w stosunku do innego moba?",
    "Czy Aksolotle umrą po 10 minutach poza wodą, gdy pada na nie deszcz?",
    "Czy bazowe odczynniki są niezbędne do stworzenia podstawowych i trzeciorzędnych mikstur?",
    "Czy do osiągnięcia maksymalnej wartości zaklęć w stole do zaklinania potrzebne jest 15 biblioteczek?",
    "Czy witherowe szkielety mają 4 kratki wysokości?",
    "Czy koń szkielet jest mobem oswajalnym?",
    "Czy poziom morza lawy w netherze wynosi y=32?",
    "Czy istnieje mob, który atakuje szkieleta?",
    "Czy uderzenie pioruna w portal do netheru go aktywuje?",
    "Czy po zniszczeniu jasnogłazu wyda on taki sam dźwięk jak przy zniszczeniu szkła?",
    "Czy wither atakuje wszystkie moby?",
    "Czy da się wydobyć sypki śnieg narzędziem z zaklęciem jedwabny dotyk?",
    "Czy śnieżki zadają komukolwiek obrażenia?",
    "Czy pająk może wspinać się po lodzie?",
    "Czy można rozmnożyć papugi w Minecrafcie?",
    "Czy witherowe szkielety mogą pojawić się na obszarze, w którym poziom światła wynosi 7?",
    "Czy shulkera można złapać do jajka?",
    "Czy da się nazwać krowę grzybową?",
    "Czy 1+2x2",
    "Czy pierwszą wersję Minecrafta stworzyła tylko jedna osoba?",
    "Czy sawanna to jedyny biom, na którym naturalnie występują akacje?",
    "Czy slimy skaczą tylko w linii prostej?",
    "Czy na /warp parkour da się latać?",
    "Czy młoda krowa grzybowa ma na plecach grzyby?",
    "Czy serwer był kiedyś na wersji 1.8?",
    "Czy na serwerze jest 15 ogrodzeń działki do wybrania?",
    "Czy wither przywraca sobie życie zabijając moby?",
    "Czy ghast widzi graczy z maksymalnie 64 metrów?",
    "Czy moby pasywne mogą zaatakować gracza w jakimś przypadku?",
    "Czy gdy nakarmimy papugę ciastkiem to otruje się i umrze?",
    "8 kroków w netherze równa się 1 krokowi w normalnym świecie?",
    "Jeżeli piorun trafi w slime, to ten zamieni się w kostkę magmy?",
    "Czy platforma na którą gracz jest teleportowany po wejściu do endu ma dokładne wymiary 4x4x1?",
    "Czy w netherze można uzyskać wodę niszcząc blok lodu?",
    "Czy nadzorca jest bossem?",
    "Czy moba moshroom da się rozmnożyć pszenicą klikając na niego lewym przyciskiem myszy trzymając produkt spożywczy?",
    "Czy Minecraft miał swoją oficjalną premierę 18 listopada 2011 roku?",
    "Czy wither respi się dzięki ułożeniu 5 bloków piasku dusz na kształt litery T i stawiając na jej górze 3 czaszki witherowych szkieletów?",
    "Czy bloki kości generują się naturalnie tylko w netherze?",
    "Czy pierwsza oryginalna nazwa Minecrafta to Cave Game?",
    "Czy jedna doba w Minecraft trwa 25 minut?",
    "Czy drewniany miecz zadaje takie same obrażenia jak złoty miecz?",
    "Czy spód Stołu Rzemieślniczego ma teksturę desek świerkowych?",
    "Czy były kiedyś inne tryby na serwerze niż FreeBuild?",
    "Czy da się nazwać krowę grzybową?",
    "Czy można zdobyć głowę ghasta?",
    "Czy widać lód pod wodą?",
    "Czy na naszym TeamSpeaku istnieje kanał Pogadanki z administracją?",
    "Czy woda zadaje obrażenia slimowi?",
    "Czy kolorowy nick metodą płatności PSC kosztuje 8 zł?",
    "Czy na /warp receptury jest 18 receptur?",
    "Czy jest /warp regulamin?",
    "Czy wszystkich dostępnych topków na serwerze jest 10?",
    "Czy na forum jest aktualnie rekrutacja na budowniczego?",
    "Czy na serwerze była kiedyś ranga NewMod?",
    "Czy enderman nie teleportuje się gdy walimy w jego nogi?",
    "Czy ocelot dostaje obrażenia od upadku?",
    "Czy pigman nie dostaje obrażeń od ognia?",
    "Czy golemy i slime nie umieją pływać?",
    "Czy pająki jaskiniowe są większe od zwykłych pająków?",
    "Czy po zabiciu golema wypada z niego czerwony tulipan?",
    "Czy możemy spalić blok netherracka?",
    "Czy po zabiciu pająka leci jego oko i pajęczyna?",
    "Czy jest możliwe skakanie po miodzie, aby ten nas nie przyklejał?",
    "Czy magma zadaje nam obrażenia jak na niej kucamy?",
    "Aby slimeblock nas odbił, trzeba skoczyć na krawędź tego bloku?",
    "Czy piorun jest w stanie podpalić żelazny blok?",
    "Jak piorun trafi w villagera, to ten zamieni się w zombie villagera?",
    "Czy w Minecraft jest 16 kolorów wełny?",
    "Czy jest w Minecraft szkło, które możemy zebrać ręką bez jego pęknięcia?",
    "Czy nietoperze palą się w dzień?",
    "Czy jest możliwość, aby szkielety strzelały do siebie nawzajem?",
    "Czy totem się aktywuje, gdy zabijemy lisa który trzyma go w pysku?",
    "Czy mały piglin weźmie do ręki totem, jak mu się rzuci?",
    "Czy da się endermana trafić strzałą?",
    "Czy drewniany murek robi się z 6 sztuk desek?",
    "Czy da się zrobić podświetloną tabliczkę w sklepie na działce?",
    "Czy ciasto robi się z 2 jajek?",
    ];

    const questionsContainer = document.getElementById('questionsContainer');

    questions.forEach((question, index) => {
        const div = document.createElement('div');
        div.classList.add('question');
        div.innerHTML = `
            <button class="copy-button" onclick="copyText('&7[&c&lPytanie&7] &b${question}', this)">Kopiuj</button>
            <p>${question}</p>
        `;
        questionsContainer.appendChild(div);
    });

    function copyText(text, button) {
        const el = document.createElement('textarea');
        el.value = text;
        document.body.appendChild(el);
        el.select();
        document.execCommand('copy');
        document.body.removeChild(el);
        button.classList.add('copied');
        button.disabled = true; 
    }

    function goBack() {
        window.history.back();
    }