const dictionary = {
    
"Podręczny piec hutniczy - automatycznie przepala!": "PODRĘCZNY PIEC Z /RECEPTURY",
"Latarka - Oświetla drogę przez 5 min!": "LATARKA Z /RECEPTURY",
"Różdzka teleportacji do miejsca śmierci!": "RÓŻDZKA TELEPORTACJI Z /RECEPTURY",
"> Super Odrzut <": "SUPER ODRZUT Z /RECEPTURY",
"> Super Kusza <": "SUPER KUSZA Z /RECEPTURY",
"> Kupon na serwerowe lotto! <": "KUPON LOTTO Z /RECEPTURY",
"Klucz do magicznych skrzynek": "KLUCZ DO SKRZYNEK Z /RECEPTURY",
"> Skrzynka z memem <": "SKRZYNKA MEM Z /RECEPTURY",
"Rurka do oddychania pod wodą (5 minut)": "RURKA DO ODDYCHANIA Z /RECEPTURY",
"Cobel niespodzianka KLIK!": "COBBLEX Z /RECEPTURY",
    
    
    
    
    
    "Netherrack(Skała Netheru)": "netherrack",
    "Mikstura szybkości (Długa)": "potionofspeedlevel2",
    "Miotana mikstura szybkości (Długa)": "splashspeed2pot",
    "Mikstura mistrza żółwi": "potionofturtlemaster2",
    "Świecąca dynia": "jack_o_lantern",
    "Wiśniowy pień": "cherry_log",
    "Wiśniowe liście": "cherry_leaves",
    "Wiśniowe deski": "cherry_planks",
    "Wiśniowa płyta": "cherry_slab",
    "Wiśniowa tabliczka": "cherry_sign",

		"Kamień endu": "endstone",
		"Mikstura życia": "potionofhealinglevelii",
		"Mikstura siły": "potionofstrengthlevelii",
		"Mikstura powolnego opadania (Długa)": "potionofslowfalling2",
		"Miotana mikstura odporności na ogień (Długa)": "potionoffireresistance2",
		"Mikstura niewykonalna": "potion",
		"Piaskowiec": "sandstone",
		"Piasek dusz": "soulsand",
		"Drewniania siekiera": "woodenaxe",
		"Kamień szlifierski": "grindstone",
		"Wiaderko wody": "waterbucket",
		"Wiaderko lawy": "lavabucket",
		"Miotana mikstura obrażeń": "splashdamagestrongpotion",
		"Miotana mikstura spowolnienia": "splashslownesslevel2pot",
		"Ochrona przed ogniem": "fireprotection",
		"Ochrona przed pociskami": "projectile_protection",
    
    "Miotana mikstura trucizny": "splashpoisonpot",
    "Miotana mikstura osłabienia (Długa)": "splashweaknesslevel2pot",
    "Miotana mikstura osłabienia": "splashweaknesspot",
    "Ochrona przed wybuchem": "blast_protection",
    "Miotana mikstura powolnego opadania (Długa)": "splashslowfalling2potion",
    "Butelki EXP": "experiencebottle",
    "Miotana mikstura siły": "splashstrengthiipotion",
    "Skrzynia kresu": "enderchest",
    "mikstura siły": "potionofstrengthlevelii",
    "Miotana mikstura szybkości": "splashspeedleveliipotion",
    "Mikstura szybkości": "potionofspeedii",
    "Powolne opadanie": "feather_falling",
    "Mikstura niewidzialności (Długa)": "potionofinvisibility2",
    "Złote jabłko KOX": "enchantedgoldenapple",
    "Oddychanie pod wodą": "respiration",
    "Wydajność pod wodą": "aqua_affinity",
    "Ciernie": "thorns",
    "Przemykanie": "swift_sneak",
    "Głębinowy wędrowiec": "depth_strider",
    "Mroźny piechur": "frost_walker",
    "Prędkość dusz": "soul_speed",
    "Ostrość": "sharpness",
    "Odporność na ogień": "fire_protection",
    "Pogromca nieumarłych": "smite",
    "Zmora stawonogów": "bane_of_arthropods",
    "Odrzut": "knockback",
    "Zaklęty ogień": "fire_aspect",
    "Grabież": "looting",
    "Szerokie ostrze": "sweeping",
    "Moc": "power",
    "Uderzenie": "punch",
    "Płomień": "flame",
    "Nieskończoność": "infinity",
    "Lojalność": "loyalty",
    "Porażenie": "channeling",
    "Przebicie": "impaling",
    "Torpeda": "riptide",
    "Szybkie przeładowanie": "quick_charge",
    "Wielostrzał": "multishot",
    "Przeszycie": "piercing",
    "Wydajność": "efficiency",
    "Jedwabny dotyk": "silk_touch",
    "Niezniszczalność": "unbreaking",
    "Szczęście": "fortune",
    "Morska fortuna": "luck_of_the_sea",
    "Przynęta": "lure",
    "Naprawa": "mending",
    "Mikstura odporności na ogień (Długa)": "potionoffireresistancelevel2",
    "Klątwa uwiązania": "binding_curse",
    "Klątwa znikania": "vanishing_curse",
    "Ochrona": "protection",
    "Kamień": "stone",
    "Błoto": "mud",
"Granit": "granite",
"Namorzynowe deski": "mangrove_planks",
"Wypolerowany granit": "polishedgranite",
"Dioryt": "diorite",
"Wypolerowany dioryt": "polisheddiorite",
"Andezyt": "andesite",
"Wypolerowany andezyt": "polishedandesite",
"Łupek": "deepslate",
"Łupkowy bruk": "cobbleddeepslate",
"Wypolerowany łupek": "polisheddeepslate",
"Kalcyt": "calcite",
"Tuf": "tuff",
"Blok nacieku": "dripstoneblock",
"Blok trawy": "grassblock",
"Ziemia": "dirt",
"Twarda ziemia": "coarsedirt",
"Bielica": "podzol",
"Zakorzeniona ziemia": "rooteddirt",
"Szkarłatne nylium": "crimsonnylium",
"Spaczone nylium": "warpednylium",
"Bruk": "cobblestone",
"Dębowe deski": "oakplanks",
"Świerkowe deski": "spruceplanks",
"Brzozowe deski": "birchplanks",
"Tropikalne deski": "jungleplanks",
"Akacjowe deski": "acaciaplanks",
"Deski ciemnego dębu": "darkoakplanks",
"Szkarłatne deski": "crimsonplanks",
"Spaczone deski": "warpedplanks",
"Sadzonka dębu": "oaksapling",
"Sadzonka świerku": "sprucesapling",
"Sadzonka brzozy": "birchsapling",
"Sadzonka tropikalna": "junglesapling",
"Sadzonka akacji": "acaciasapling",
"Sadzonka ciemnego dębu": "darkoaksapling",
"Skała macierzysta": "bedrock",
"Piasek": "sand",
"Czerwony piasek": "redsand",
"żwir": "gravel",
"Złoże węgla": "coalore",
"Łupkowe złoże węgla": "deepslatecoalore",
"Złoże żelaza": "ironore",
"Łupkowe złoże żelaza": "deepslateironore",
"Złoże miedzi": "copperore",
"Łupkowe złoże miedzi": "deepslatecopperore",
"Ruda złota": "goldore",
"Łupkowe złoże złota": "deepslategoldore",
"Złoże redstone": "redstoneore",
"Łupkowe złoże redstone": "deepslateredstoneore",
"Złoże szmaragdu": "emeraldore",
"Łupkowe złoże szmaragdu": "deepslateemeraldore",
"Złoże lazurytu": "lapisore",
"Łupkowe złoże lazurytu": "deepslatelapisore",
"Złoże diamentu": "diamondore",
"Łupkowe złoże diamentu": "deepslatediamondore",
"Netherowe złoże złota": "nethergoldore",
"Złoże kwarcu": "netherquartzore",
"Pradawne zgliszcza": "ancientdebris",
"Blok węgla": "coalblock",
"Blok rudy żelaza": "rawironblock",
"Blok rudy miedzi": "rawcopperblock",
"Blok surowego złota": "rawgoldblock",
"Blok ametystu": "amethystblock",
"Kiełkujący ametyst": "buddingamethyst",
"Blok żelaza": "ironblock",
"Blok miedzi": "copperblock",
"Blok złota": "goldblock",
"Blok diamentu": "diamondblock",
"Blok netherytu": "netheriteblock",
"Zwietrzała miedź": "exposedcopper",
"Zaśniedziała miedź": "weatheredcopper",
"Utleniona miedź": "oxidizedcopper",
"Żłobiona miedź": "cutcopper",
"Zwietrzała żłobiona miedź": "exposedcutcopper",
"Zaśniedziała żłobiona miedź": "weatheredcutcopper",
"Utleniona żłobiona miedź": "oxidizedcutcopper",
"Żłobione miedziane schody": "cutcopperstairs",
"Zwietrzałe żłobione miedziane schody": "exposedcutcopperstairs",
"Zaśniedziałe żłobione miedziane schody": "weatheredcutcopperstairs",
"Utlenione żłobione miedziane schody": "oxidizedcutcopperstairs",
"Żłobiona miedziana płyta": "cutcopperslab",
"Zwietrzała żłobiona miedziana płyta": "exposedcutcopperslab",
"Zaśniedziała żłobiona miedziana płyta": "weatheredcutcopperslab",
"Utleniona żłobiona miedziana płyta": "oxidizedcutcopperslab",
"Woskowany blok miedzi": "waxedcopperblock",
"Woskowana zwietrzała miedź": "waxedexposedcopper",
"Woskowana zaśniedziała miedź": "waxedweatheredcopper",
"Woskowana utleniona miedź": "waxedoxidizedcopper",
"Woskowana żłobiona miedź": "waxedcutcopper",
"Woskowana zwietrzała żłobiona miedź": "waxedexposedcutcopper",
"Woskowana zaśniedziała żłobiona miedź": "waxedweatheredcutcopper",
"Woskowana utleniona żłobiona miedź": "waxedoxidizedcutcopper",
"Woskowane żłobione miedziane schody": "waxedcutcopperstairs",
"Woskowane zwietrzałe żłobione miedziane schody": "waxedexposedcutcopperstairs",
"Woskowane zaśniedziałe żłobione miedziane schody": "waxedweatheredcutcopperstairs",
"Woskowane utlenione żłobione miedziane schody": "waxedoxidizedcutcopperstairs",
"Woskowana żłobiona miedziana płyta": "waxedcutcopperslab",
"Woskowana zwietrzała żłobiona miedziana płyta": "waxedexposedcutcopperslab",
"Woskowana zaśniedziała żłobiona miedziana płyta": "waxedweatheredcutcopperslab",
"Woskowana utleniona żłobiona miedziana płyta": "waxedoxidizedcutcopperslab",
"Dębowy pień": "oaklog",
"Świerkowy pień": "sprucelog",
"Brzozowy pień": "birchlog",
"Tropikalny pień": "junglelog",
"Akacjowy pień": "acacialog",
"Drewno ciemnego dębu": "darkoaklog",
"Szkarłatny trzon": "crimsonstem",
"Spaczony trzon": "warpedstem",
"Okorowany dębowy pień": "strippedoaklog",
"Okorowany świerkowy pień": "strippedsprucelog",
"Okorowany brzozowy pień": "strippedbirchlog",
"Okorowany tropikalny pień": "strippedjunglelog",
"Okorowany akacjowy pień": "strippedacacialog",
"Okorowany ciemnodębowy pień": "strippeddarkoaklog",
"Ociosany szkarłatny trzon": "strippedcrimsonstem",
"Ociosany spaczony trzon": "strippedwarpedstem",
"Okorowane dębowe drewno": "strippedoakwood",
"Okorowane świerkowe drewno": "strippedsprucewood",
"Okorowane brzozowe drewno": "strippedbirchwood",
"Okorowane tropikalne drewno": "strippedjunglewood",
"Okorowane akacjowe drewno": "strippedacaciawood",
"Okorowane ciemnodębowe drewno": "strippeddarkoakwood",
"Ociosane szkarłatne strzępki": "strippedcrimsonhyphae",
"Ociosane spaczone strzępki": "strippedwarpedhyphae",
"Dębowe drewno": "oakwood",
"Świerkowe drewno": "sprucewood",
"Brzozowe drewno": "birchwood",
"Tropikalne drewno": "junglewood",
"Akacjowe drewno": "acaciawood",
"Ciemnodębowe drewno": "darkoakwood",
"Szkarłatne strzępki": "crimsonhyphae",
"Spaczone strzępki": "warpedhyphae",
"Dębowe liście": "oakleaves",
"Świerkowe liŚcie": "spruceleaves",
"Brzozowe liŚcie": "birchleaves",
"Tropikalne liście": "jungleleaves",
"Akacjowe liście": "acacialeaves",
"Ciemnodębowe liście": "darkoakleaves",
"Liście azalii": "azalealeaves",
"Kwitnące liście azalii": "floweringazalealeaves",
"Gąbka": "sponge",
"Mokra gąbka": "wetsponge",
"Szkło": "glass",
"Przyciemnione szkło": "tintedglass",
"Blok lazurytu": "lapisblock",
"Piasek": "sand",
"Rzeźbiony piaskowiec": "chiseledsandstone",
"Przycięty piaskowiec": "cutsandstone",
"Pajęczyna": "cobweb",
"Trawa": "grass",
"Paproć": "fern",
"Azalia": "azalea",
"Kwitnąca azalia": "floweringazalea",
"Uschnięty krzak": "deadbush",
"Trawa morska": "seagrass",
"Iskrzyłuda": "seapickle",
"Biała wełna": "whitewool",
"Pomarańczowa wełna": "orangewool",
"Karmazynowa wełna": "magentawool",
"Jasnoniebieska wełna": "lightbluewool",
"Żółta wełna": "yellowwool",
"Jasnozielona wełna": "limewool",
"Różowa wełna": "pinkwool",
"Szara wełna": "graywool",
"Jasnoszara wełna": "lightgraywool",
"Błękitna wełna": "cyanwool",
"Fioletowa wełna": "purplewool",
"Niebieska wełna": "bluewool",
"Brązowa wełna": "brownwool",
"Zielona wełna": "greenwool",
"Czerwona wełna": "redwool",
"Czarna wełna": "blackwool",
"Mlecz": "dandelion",
"Mak": "poppy",
"Niebieska orchidea": "blueorchid",
"Czosnek": "allium",
"Houstonia błękitna": "azurebluet",
"Czerwony tulipan": "redtulip",
"Pomarańczowy tulipan": "orangetulip",
"Biały tulipan": "whitetulip",
"Różowe kwiatki": "pinktulip",
"Margaretka": "oxeyedaisy",
"Chaber": "cornflower",
"Konwalia": "lilyofthevalley",
"Róża Witherowa": "witherrose",
"Pylikwiat": "sporeblossom",
"Brązowy grzyb": "brownmushroom",
"Czerwony grzyb": "redmushroom",
"Szkarłatny grzyb": "crimsonfungus",
"Spaczony grzyb": "warpedfungus",
"Szkarłatne korzenie": "crimsonroots",
"Spaczone korzenie": "warpedroots",
"Netherowe kiełki": "nethersprouts",
"Lamentorośl": "weepingvines",
"Krętorośl": "twistingvines",
"Trzcina": "sugarcane",
"Wodorost": "kelp",
"Warstwa mchu": "mosscarpet",
"Blok mchu": "mossblock",
"Zwisające korzenie": "hangingroots",
"Wielki spadkoliść": "bigdripleaf",
"Mały spadkoliść": "smalldripleaf",
"Bambus": "bamboo",
"Dębowa płyta": "oakslab",
"Świerkowa płyta": "spruceslab",
"Brzozowa płyta": "birchslab",
"Tropikalna płyta": "jungleslab",
"Akacjowa płyta": "acaciaslab",
"Ciemnodębowa płyta": "darkoakslab",
"Szkarłatna płyta": "crimsonslab",
"Spaczona płyta": "warpedslab",
"Kamienna płyta": "stoneslab",
"Gładka kamienna płyta": "smoothstoneslab",
"Piaskowcowa płyta": "sandstoneslab",
"Przycięta piaskowcowa płyta": "cutsandstoneslab",
"Skamieniała dębowa płyta": "petrifiedoakslab",
"Półpłytka z bruku": "cobblestoneslab",
"Ceglana płyta": "brickslab",
"Kamienna ceglana płyta": "stonebrickslab",
"Netherowa ceglana płyta": "netherbrickslab",
"Kwarcowa płyta": "quartzslab",
"Czerwona piaskowcowa płyta": "redsandstoneslab",
"Przycięta czerwona piaskowcowa płyta": "cutredsandstoneslab",
"Purpurowa płyta": "purpurslab",
"Pryzmarynowa płyta": "prismarineslab",
"Pryzmarynowa ceglana płyta": "prismarinebrickslab",
"Ciemna pryzmarynowa płyta": "darkprismarineslab",
"Gładki blok kwarcu": "smoothquartz",
"Gładki czerwony piaskowiec": "smoothredsandstone",
"Gładki piaskowiec": "smoothsandstone",
"Gładki kamień": "smoothstone",
"Cegły": "bricks",
"Biblioteczka": "bookshelf",
"Zamszony bruk": "mossycobblestone",
"Obsydian": "obsidian",
"Pochodnia": "torch",
"Endowy słupek": "endrod",
"Łodyga refrenusu": "chorusplant",
"Kwiat refrenusu": "chorusflower",
"Blok purpuru": "purpurblock",
"Purpurowy filar": "purpurpillar",
"Purpurowe schody": "purpurstairs",
"Spawner": "spawner",
"Dębowe schody": "oakstairs",
"Skrzynka": "chest",
"Stół rzemieślniczy": "craftingtable",
"Pole uprawne": "farmland",
"Piecyk": "furnace",
"Drabinka": "ladder",
"Brukowe schody": "cobblestonestairs",
"Śnieg": "snow",
"Lód": "ice",
"Blok śniegu": "snowblock",
"Kaktus": "cactus",
"Glina": "clay",
"Szafa grająca": "jukebox",
"Płotek dębowy": "oakfence",
"Płotek świerkowy": "sprucefence",
"Płotek brzozowy": "birchfence",
"Płotek tropikalny": "junglefence",
"Płotek akacjowy": "acaciafence",
"Płotek ciemnodębowy": "darkoakfence",
"Płotek szkarłatny": "crimsonfence",
"Płotek spaczony": "warpedfence",
"Dynia": "pumpkin",
"Wykrawana dynia": "carvedpumpkin",
"Netherrack": "netherrack",
"Gleba dusz": "soulsoil",
"Bazalt": "basalt",
"Wypolerowany bazalt": "polishedbasalt",
"Gładki bazalt": "smoothbasalt",
"Eteryczna pochodnia": "soultorch",
"Jasnogłaz": "glowstone",
"Zarobaczony kamień": "infestedstone",
"Zarobaczony bruk": "infestedcobblestone",
"Zarobaczone kamienne cegły": "infestedstonebricks",
"Zarobaczone zamszone kamienne cegły": "infestedmossystonebricks",
"Zarobaczone popękane kamienne cegły": "infestedcrackedstonebricks",
"Zarobaczone rzeźbione kamienne cegły": "infestedchiseledstonebricks",
"Zarobaczony łupek": "infesteddeepslate",
"Kamienne cegły": "stonebricks",
"Zamszone kamienne cegły": "mossystonebricks",
"Popękane kamienne cegły": "crackedstonebricks",
"Rzeźbione kamienne cegły": "chiseledstonebricks",
"Łupkowe cegły": "deepslatebricks",
"Popękane łupkowe cegły": "crackeddeepslatebricks",
"Łupkowe kafelki": "deepslatetiles",
"Popękane łupkowe kafelki": "crackeddeepslatetiles",
"Rzeźbiony łupek": "chiseleddeepslate",
"Blok borowika": "brownmushroomblock",
"Blok muchomora": "redmushroomblock",
"Trzon grzyba": "mushroomstem",
"Żelazne kraty": "ironbars",
"Łańcuch": "chain",
"Szyba": "glasspane",
"Arbuz": "melon",
"Pnącza": "vine",
"Świecący porost": "glowlichen",
"Ceglane schody": "brickstairs",
"Schody z kamiennych cegieł": "stonebrickstairs",
"Grzybnia": "mycelium",
"Lilia wodna": "lilypad",
"Netherowe cegły": "netherbricks",
"Popękane netherowe cegły": "crackednetherbricks",
"Rzeźbione netherowe cegły": "chiselednetherbricks",
"Netherowy ceglany płot": "netherbrickfence",
"Netherowe ceglane schody": "netherbrickstairs",
"Stół do zaklinowania": "enchantingtable",
"Rama portalu do Endu": "endportalframe",
"Kamień Endu": "endstone",
"Endowe kamienne cegły": "endstonebricks",
"Smocze jajo": "dragonegg",
"Piaskowcowe schody": "sandstonestairs",
"Blok szmaragdu": "emeraldblock",
"Świerkowe schody": "sprucestairs",
"Brzozowe schody": "birchstairs",
"Tropikalne schody": "junglestairs",
"Szkarłatne schody": "crimsonstairs",
"Spaczone schody": "warpedstairs",
"Blok poleceń": "commandblock",
"Magiczna latarnia": "beacon",
"Brukowy murek": "cobblestonewall",
"Zamszony brukowy murek": "mossycobblestonewall",
"Ceglany murek": "brickwall",
"Pryzmarynowy murek": "prismarinewall",
"Czerwony piaskowcowy murek": "redsandstonewall",
"Zamszony kamienny ceglany murek": "mossystonebrickwall",
"Granitowy murek": "granitewall",
"Kamienny ceglany murek": "stonebrickwall",
"Netherowy ceglany murek": "netherbrickwall",
"Andezytowy murek": "andesitewall",
"Czerwony netherowy ceglany murek": "rednetherbrickwall",
"Piaskowcowy murek": "sandstonewall",
"Endowy kamienny ceglany murek": "endstonebrickwall",
"Diorytowy murek": "dioritewall",
"Czernitowy murek": "blackstonewall",
"Wypolerowany czernitowy murek": "polishedblackstonewall",
"Wypolerowany czernitowy ceglany murek": "polishedblackstonebrickwall",
"Łupkowy brukowy murek": "cobbleddeepslatewall",
"Wypolerowany łupkowy murek": "polisheddeepslatewall",
"Łupkowy ceglany murek": "deepslatebrickwall",
"Łupkowy kafelkowy murek": "deepslatetilewall",
"Kowadło": "anvil",
"Wyszczerbione kowadło": "chippedanvil",
"Uszkodzone kowadło": "damagedanvil",
"Rzeźbiony blok kwarcu": "chiseledquartzblock",
"Blok kwarcu": "quartzblock",
"Kwarcowe cegły": "quartzbricks",
"Kwarcowy filar": "quartzpillar",
"Kwarcowe schody": "quartzstairs",
"Biała glazurowa terakota": "whiteterracotta",
"Pomarańczowa glazurowa terakota": "orangeterracotta",
"Karmazynowa glazurowa terakota": "magentaterracotta",
"Jasnoniebieska glazurowa terakota": "lightblueterracotta",
"Żółta glazurowa terakota": "yellowterracotta",
"Jasnozielona glazurowa terakota": "limeterracotta",
"Różowa glazurowa terakota": "pinkterracotta",
"Szara glazurowa terakota": "grayterracotta",
"Jasnoszara glazurowa terakota": "lightgrayterracotta",
"Błękitna glazurowa terakota": "cyanterracotta",
"Fioletowa glazurowa terakota": "purpleterracotta",
"Niebieska glazurowa terakota": "blueterracotta",
"Brązowa glazurowa terakota": "brownterracotta",
"Zielona glazurowa terakota": "greenterracotta",
"Czerwona glazurowa terakota": "redterracotta",
"Czarna glazurowa terakota": "blackterracotta",
"Bariera": "barrier",
"Światło": "light",
"Snop siana": "hayblock",
"Biały dywan": "whitecarpet",
"Pomarańczowy dywan": "orangecarpet",
"Karmazynowy dywan": "magentacarpet",
"Jasnoniebieski dywan": "lightbluecarpet",
"Żółty dywan": "yellowcarpet",
"Jasnozielony dywan": "limecarpet",
"Różowy dywan": "pinkcarpet",
"Szary dywan": "graycarpet",
"Jasnoszary dywan": "lightgraycarpet",
"Błękitny dywan": "cyancarpet",
"Fioletowy dywan": "purplecarpet",
"Niebieski dywan": "bluecarpet",
"Brązowy dywan": "browncarpet",
"Zielony dywan": "greencarpet",
"Czerwony dywan": "redcarpet",
"Czarny dywan": "blackcarpet",
"Terakota": "terracotta",
"Zbity lód": "packedice",
"Akacjowe schody": "acaciastairs",
"Ciemnodębowe schody": "darkoakstairs",
"Ścieżka": "dirtpath",
"Słonecznik": "sunflower",
"Bez": "lilac",
"Krzew róży": "rosebush",
"Piwonia": "peony",
"Wysoka trawa": "tallgrass",
"Duża paproć": "largefern",
"Białe szkło": "whitestainedglass",
"Pomarańczowe szkło": "orangestainedglass",
"Karmazynowe szkło": "magentastainedglass",
"Jasnoniebieskie szkło": "lightbluestainedglass",
"Żółte szkło": "yellowstainedglass",
"Jasnozielone szkło": "limestainedglass",
"Różowe szkło": "pinkstainedglass",
"Szare szkło": "graystainedglass",
"Jasnoszare szkło": "lightgraystainedglass",
"Błękitne szkło": "cyanstainedglass",
"Fioletowe szkło": "purplestainedglass",
"Niebieskie szkło": "bluestainedglass",
"Brązowe szkło": "brownstainedglass",
"Zielone szkło": "greenstainedglass",
"Czerwone szkło": "redstainedglass",
"Czarne szkło": "blackstainedglass",
"Biała szyba": "whitestainedglasspane",
"Pomarańczowa szyba": "orangestainedglasspane",
"Karmazynowa szyba": "magentastainedglasspane",
"Jasnoniebieska szyba": "lightbluestainedglasspane",
"Żółta szyba": "yellowstainedglasspane",
"Jasnozielona szyba": "limestainedglasspane",
"Różowa szyba": "pinkstainedglasspane",
"Szara szyba": "graystainedglasspane",
"Jasnoszara szyba": "lightgraystainedglasspane",
"Błękitna szyba": "cyanstainedglasspane",
"Fioletowa szyba": "purplestainedglasspane",
"Niebieska szyba": "bluestainedglasspane",
"Brązowa szyba": "brownstainedglasspane",
"Zielona szyba": "greenstainedglasspane",
"Czerwona szyba": "redstainedglasspane",
"Czarna szyba": "blackstainedglasspane",
"Pryzmaryn": "prismarine",
"Pryzmarynowe cegły": "prismarinebricks",
"Ciemny pryzmaryn": "darkprismarine",
"Pryzmarynowe schody": "prismarinestairs",
"Pryzmarynowe ceglane schody": "prismarinebrickstairs",
"Ciemne pryzmarynowe schody": "darkprismarinestairs",
"Latarnia morska": "sealantern",
"Czerwony piaskowiec": "redsandstone",
"Rzeźbiony czerwony piaskowiec": "chiseledredsandstone",
"Przycięty czerwony piaskowiec": "cutredsandstone",
"Schody z czerwonego piaskowca": "redsandstonestairs",
"Powtarzający blok poleceń": "repeatingcommandblock",
"Łańcuchowy blok poleceń": "chaincommandblock",
"Blok magmy": "magmablock",
"Blok netherowych brodawek": "netherwartblock",
"Blok spaczonych brodawek": "warpedwartblock",
"Czerwone netherowe cegły": "rednetherbricks",
"Blok z kości": "boneblock",
"Pustka strukturalna": "structurevoid",
"Shulkerowa skrzynia": "shulkerbox",
"Biała shulkerowa skrzynia": "whiteshulkerbox",
"Pomarańczowa shulkerowa skrzynia": "orangeshulkerbox",
"Karmazynowa shulkerowa skrzynia": "magentashulkerbox",
"Jasnoniebieska shulkerowa skrzynia": "lightblueshulkerbox",
"Żółta shulkerowa skrzynia": "yellowshulkerbox",
"Jasnozielona shulkerowa skrzynia": "limeshulkerbox",
"Różowa shulkerowa skrzynia": "pinkshulkerbox",
"Szara shulkerowa skrzynia": "grayshulkerbox",
"Jasnoszara shulkerowa skrzynia": "lightgrayshulkerbox",
"Błękitna shulkerowa skrzynia": "cyanshulkerbox",
"Fioletowa shulkerowa skrzynia": "purpleshulkerbox",
"Niebieska shulkerowa skrzynia": "blueshulkerbox",
"Brązowa shulkerowa skrzynia": "brownshulkerbox",
"Zielona shulkerowa skrzynia": "greenshulkerbox",
"Czerwona shulkerowa skrzynia": "redshulkerbox",
"Czarna shulkerowa skrzynia": "blackshulkerbox",
"Biała glazurowana terakota": "whiteglazedterracotta",
"Pomarańczowa glazurowana terakota": "orangeglazedterracotta",
"Karmazynowa glazurowana terakota": "magentaglazedterracotta",
"Jasnoniebieska glazurowana terakota": "lightblueglazedterracotta",
"Żółta glazurowana terakota": "yellowglazedterracotta",
"Jasnozielona glazurowana terakota": "limeglazedterracotta",
"Różowa glazurowana terakota": "pinkglazedterracotta",
"Szara glazurowana terakota": "grayglazedterracotta",
"Jasnoszara glazurowana terakota": "lightgrayglazedterracotta",
"Błękitna glazurowana terakota": "cyanglazedterracotta",
"Fioletowa glazurowana terakota": "purpleglazedterracotta",
"Niebieska glazurowana terakota": "blueglazedterracotta",
"Brązowa glazurowana terakota": "brownglazedterracotta",
"Zielona glazurowana terakota": "greenglazedterracotta",
"Czerwona glazurowana terakota": "redglazedterracotta",
"Czarna glazurowana terakota": "blackglazedterracotta",
"Biały beton": "whiteconcrete",
"Pomarańczowy beton": "orangeconcrete",
"Karmazynowy beton": "magentaconcrete",
"Jasnoniebieski beton": "lightblueconcrete",
"Żółty beton": "yellowconcrete",
"Jasnozielony beton": "limeconcrete",
"Różowy beton": "pinkconcrete",
"Szary beton": "grayconcrete",
"Jasnoszary beton": "lightgrayconcrete",
"Błękitny beton": "cyanconcrete",
"Fioletowy beton": "purpleconcrete",
"Niebieski beton": "blueconcrete",
"Brązowy beton": "brownconcrete",
"Zielony beton": "greenconcrete",
"Czerwony beton": "redconcrete",
"Czarny beton": "blackconcrete",
"Biały cement": "whiteconcretepowder",
"Pomarańczowy cement": "orangeconcretepowder",
"Karmazynowy cement": "magentaconcretepowder",
"Jasnoniebieski cement": "lightblueconcretepowder",
"Żółty cement": "yellowconcretepowder",
"Jasnozielony cement": "limeconcretepowder",
"Różowy cement": "pinkconcretepowder",
"Szary cement": "grayconcretepowder",
"Jasnoszary cement": "lightgrayconcretepowder",
"Błękitny cement": "cyanconcretepowder",
"Fioletowy cement": "purpleconcretepowder",
"Niebieski cement": "blueconcretepowder",
"Brązowy cement": "brownconcretepowder",
"Zielony cement": "greenconcretepowder",
"Czerwony cement": "redconcretepowder",
"Czarny cement": "blackconcretepowder",
"Żółwie jajko": "turtleegg",
"Blok martwego koralowca rurkowatego": "deadtubecoralblock",
"Blok martwego koralowca mózgowatego": "deadbraincoralblock",
"Blok martwego koralowca bąbelkowatego": "deadbubblecoralblock",
"Blok martwego koralowca ognistego": "deadfirecoralblock",
"Blok martwego koralowca rogatego": "deadhorncoralblock",
"Blok koralowca rurkowatego": "tubecoralblock",
"Blok koralowca mózgowatego": "braincoralblock",
"Blok koralowca bąbelkowatego": "bubblecoralblock",
"Blok koralowca ognistego": "firecoralblock",
"Blok koralowca rogatego": "horncoralblock",
"Koralowiec rurkowaty": "tubecoral",
"Koralowiec mózgowaty": "braincoral",
"Koralowiec bąbelkowaty": "bubblecoral",
"Koralowiec ognisty": "firecoral",
"Koralowiec rogaty": "horncoral",
"Martwy koralowiec mózgowaty": "deadbraincoral",
"Martwy koralowiec bąbelkowy": "deadbubblecoral",
"Martwy koralowiec ognisty": "deadfirecoral",
"Martwy koralowiec rogaty": "deadhorncoral",
"Martwy koralowiec rurkowaty": "deadtubecoral",
"Wachlarz koralowca rurkowatego": "tubecoralfan",
"Wachlarz koralowca mózgowatego": "braincoralfan",
"Wachlarz koralowca bąbelkowatego": "bubblecoralfan",
"Wachlarz koralowca ognistego": "firecoralfan",
"Wachlarz koralowca rogatego": "horncoralfan",
"Martwy wachlarz koralowca rurkowatego": "deadtubecoralfan",
"Martwy wachlarz koralowca mózgowatego": "deadbraincoralfan",
"Martwy wachlarz koralowca bąbelkowatego": "deadbubblecoralfan",
"Martwy wachlarz koralowca ognistego": "deadfirecoralfan",
"Martwy wachlarz koralowca rogatego": "deadhorncoralfan",
"Niebieski lód lodowcowy": "blueice",
"Przewodnia": "conduit",
"Wypolerowane granitowe schody": "polishedgranitestairs",
"Gładkie czerwone piaskowcowe schody": "smoothredsandstonestairs",
"Zamszone kamienne ceglane schody": "mossystonebrickstairs",
"Wypolerowane diorytowe schody": "polisheddioritestairs",
"Zamszone brukowe schody": "mossycobblestonestairs",
"Endowe kamienne ceglane schody": "endstonebrickstairs",
"Kamienne schody": "stonestairs",
"Gładkie piaskowcowe schody": "smoothsandstonestairs",
"Gładkie kwarcowe schody": "smoothquartzstairs",
"Granitowe schody": "granitestairs",
"Andezytowe schody": "andesitestairs",
"Czerwone netherowe ceglane schody": "rednetherbrickstairs",
"Wypolerowane andezytowe schody": "polishedandesitestairs",
"Diorytowe schody": "dioritestairs",
"Łupkowe brukowe schody": "cobbleddeepslatestairs",
"Wypolerowana łupkowa schody": "polisheddeepslatestairs",
"Łupkowe ceglane schody": "deepslatebrickstairs",
"Łupkowe kafelkowe schody": "deepslatetilestairs",
"Wypolerowana granitowa płyta": "polishedgraniteslab",
"Gładka czerwona piaskowcowa płyta": "smoothredsandstoneslab",
"Zamszona kamienna ceglana płyta": "mossystonebrickslab",
"Wypolerowana diorytowa płyta": "polisheddioriteslab",
"Zamszona brukowa płyta": "mossycobblestoneslab",
"Endowa kamienna ceglana płyta": "endstonebrickslab",
"Gładka piaskowcowa płyta": "smoothsandstoneslab",
"Gładka kwarcowa płyta": "smoothquartzslab",
"Granitowa płyta": "graniteslab",
"Andezytowa płyta": "andesiteslab",
"Czerwona netherowa ceglana płyta": "rednetherbrickslab",
"Wypolerowana andezytowa płyta": "polishedandesiteslab",
"Diorytowa płyta": "dioriteslab",
"Łupkowa brukowa płyta": "cobbleddeepslateslab",
"Wypolerowana łupkowa płyta": "polisheddeepslateslab",
"Łupkowa ceglana płyta": "deepslatebrickslab",
"Łupkowa kafelkowa płyta": "deepslatetileslab",
"Rusztowanie": "scaffolding",
"Redstone": "redstone",
"Pochodnia redstone": "redstonetorch",
"Blok redstone": "redstoneblock",
"Przekaźnik": "repeater",
"Komparator": "comparator",
"Tłok": "piston",
"Lepki tłok": "stickypiston",
"Blok szlamu": "slimeblock",
"Blok miodu": "honeyblock",
"Detektor": "observer",
"Lej": "hopper",
"Dozownik": "dispenser",
"Podajnik": "dropper",
"Pulpit": "lectern",
"Tarcza strzelecka": "target",
"Dźwignia": "lever",
"Piorunochron": "lightningrod",
"Detektor światła dziennego": "daylightdetector",
"Skulkowy czujnik": "sculksensor",
"Zaczep na linkę": "tripwirehook",
"Skrzynia-pułapka": "trappedchest",
"TNT": "tnt",
"Lampa": "redstonelamp",
"Blok dźwiękowy": "noteblock",
"Kamienny przycisk": "stonebutton",
"Wypolerowany czernitowy przycisk": "polishedblackstonebutton",
"Dębowy przycisk": "oakbutton",
"Świerkowy przycisk": "sprucebutton",
"Brzozowy przycisk": "birchbutton",
"Tropikalny przycisk": "junglebutton",
"Akacjowy przycisk": "acaciabutton",
"Ciemnodębowy przycisk": "darkoakbutton",
"Szkarłatny przycisk": "crimsonbutton",
"Spaczony przycisk": "warpedbutton",
"Kamienna płyta naciskowa": "stonepressureplate",
"Wypolerowana czernitowa płytka naciskowa": "polishedblackstonepressureplate",
"Lekka płyta naciskowa": "lightweightedpressureplate",
"Ciężka płyta naciskowa": "heavyweightedpressureplate",
"Dębowa płyta naciskowa": "oakpressureplate",
"Świerkowa płyta naciskowa": "sprucepressureplate",
"Brzozowa płyta naciskowa": "birchpressureplate",
"Tropikalna płyta naciskowa": "junglepressureplate",
"Akacjowa płyta naciskowa": "acaciapressureplate",
"Ciemnodębowa płyta naciskowa": "darkoakpressureplate",
"Szkarłatna płyta naciskowa": "crimsonpressureplate",
"Spaczona płyta naciskowa": "warpedpressureplate",
"Drewniane drzwi": "oakdoor",
		"Żelazne drzwi": "irondoor",
"Dębowe drzwi": "oakdoor",
"Świerkowe drzwi": "sprucedoor",
"Brzozowe drzwi": "birchdoor",
"Tropikalne drzwi": "jungledoor",
"Akacjowe drzwi": "acaciadoor",
"Ciemnodębowe drzwi": "darkoakdoor",
"Szkarłatne drzwi": "crimsondoor",
"Spaczone drzwi": "warpeddoor",
"Żelazna klapa": "irontrapdoor",
"Właz dębowy": "oaktrapdoor",
"Świerkowa klapa": "sprucetrapdoor",
"Brzozowa klapa": "birchtrapdoor",
"Tropikalna klapa": "jungletrapdoor",
"Akacjowa klapa": "acaciatrapdoor",
"Ciemnodębowa klapa": "darkoaktrapdoor",
"Szkarłatna klapa": "crimsontrapdoor",
"Spaczona klapa": "warpedtrapdoor",
"Dębowa furtka": "oakfencegate",
"Świerkowa furtka": "sprucefencegate",
"Brzozowa furtka": "birchfencegate",
"Tropikalna furtka": "junglefencegate",
"Akacjowa furtka": "acaciafencegate",
"Ciemnodębowa furtka": "darkoakfencegate",
"Szkarłatna furtka": "crimsonfencegate",
"Spaczona furtka": "warpedfencegate",
"Zasilane tory": "poweredrail",
"Tory z czujnikiem": "detectorrail",
"Tory": "rail",
"Tory aktywacyjne": "activatorrail",
"Siodło": "saddle",
"Wagonik": "minecart",
"Wagonik ze skrzynią": "chestminecart",
"Napędzany wagonik": "furnaceminecart",
"Wagonik z TNT": "tntminecart",
"Wagonik z lejem": "hopperminecart",
"Marchewka na patyku": "carrotonastick",
"Spaczony grzyb na patyku": "warpedfungusonastick",
"Elytry": "elytra",
"Dębowa łódka": "oakboat",
"Świetkowa łódka": "spruceboat",
"Brzozowa łódka": "birchboat",
"Tropikalna łódka": "jungleboat",
"Akacjowa łódka": "acaciaboat",
"Ciemnodębowa łódka": "darkoakboat",
"Blok struktur": "structureblock",
"Blok konstrukcyjny": "jigsaw",
"Żółwia skorupa": "turtlehelmet",
"Tarczka": "scute",
"Krzesiwo": "flintandsteel",
"Jabłko": "apple",
"Łuk": "bow",
"Strzała z miksturą spowolnienia (Długa)": "arrowslownesslong",
"Strzała z miksturą spowolnienia": "arrowslowness",
"Strzała": "arrow",
"Węgiel drzewny": "charcoal",
"Węgiel": "coal",
"Diament": "diamond",
"Szmaragd": "emerald",
"Lazuryt": "lapislazuli",
"Kwarc": "quartz",
"Odłamek ametystu": "amethystshard",
"Ruda żelaza": "rawiron",
"Sztabka żelaza": "ironingot",
"Ruda miedzi": "rawcopper",
"Sztabka miedzi": "copperingot",
"Surowe złoto": "rawgold",
"Sztabka złota": "goldingot",
"Sztabka netherytu": "netheriteingot",
"Odłamek netherytu": "netheritescrap",
"Drewniany miecz": "woodensword",
"Drewniana łopata": "woodenshovel",
"Drewniany kilof": "woodenpickaxe",
"Drewniania motyka": "woodenhoe",
"Kamienny miecz": "stonesword",
"Kamienna łopata": "stoneshovel",
"Kamienny kilof": "stonepickaxe",
"Kamienna siekiera": "stoneaxe",
"Kamienna motyka": "stonehoe",
"Złoty miecz": "goldensword",
"Złota łopata": "goldenshovel",
"Złoty kilof": "goldenpickaxe",
"Złota siekiera": "goldenaxe",
"Złota motyka": "goldenhoe",
"Żelazny miecz": "ironsword",
"Żelazna łopata": "ironshovel",
"Żelazny kilof": "ironpickaxe",
"Żelazna siekiera": "ironaxe",
"Żelazna motyka": "ironhoe",
"Diamentowy miecz": "diamondsword",
"Diamentowa łopata": "diamondshovel",
"Diamentowy kilof": "diamondpickaxe",
"Diamentowa siekiera": "diamondaxe",
"Diamentowa motyka": "diamondhoe",
"Netherytowy miecz": "netheritesword",
"Netherytowa łopata": "netheriteshovel",
"Netherytowy kilof": "netheritepickaxe",
"Netherytowa siekiera": "netheriteaxe",
"Netherytowa motyka": "netheritehoe",
"Patyk": "stick",
"Miska": "bowl",
"Zupa grzybowa": "mushroomstew",
"Nić": "string",
"Pióro": "feather",
"Proch strzelniczy": "gunpowder",
"Nasiona pszenicy": "wheatseeds",
"Pszenica": "wheat",
"Chleb": "bread",
"Skórzany hełm": "leatherhelmet",
"Skórzany napierśnik": "leatherchestplate",
"Skórzane nogawice": "leatherleggings",
"Skórzane buty": "leatherboots",
"Hełm kolczy": "chainmailhelmet",
"Napierśnik kolczy": "chainmailchestplate",
"Nogawice kolcze": "chainmailleggings",
"Buty kolcze": "chainmailboots",
"Żelazny hełm": "ironhelmet",
"Żelazny napierśnik": "ironchestplate",
"Żelazne nogawice": "ironleggings",
"Żelazne buty": "ironboots",
"Diamentowy hełm": "diamondhelmet",
"Diamentowy napierśnik": "diamondchestplate",
"Diamentowe nogawice": "diamondleggings",
"Diamentowe buty": "diamondboots",
"Złoty hełm": "goldenhelmet",
"Złoty napierśnik": "goldenchestplate",
"Złote nogawice": "goldenleggings",
"Złote buty": "goldenboots",
"Netherytowy hełm": "netheritehelmet",
"Netherytowy napierśnik": "netheritechestplate",
"Netherytowe nogawice": "netheriteleggings",
"Netherytowe buty": "netheriteboots",
"Krzemień": "flint",
"Surowa wieprzowina": "porkchop",
"Grilowana wieprzowina": "cookedporkchop",
"Obraz": "painting",
"Złote jabłko": "goldenapple",
"Zaklęte złote jabłko": "enchantedgoldenapple",
"Tabliczka": "oaksign",
		"Dębowa tabliczka": "oaksign",
"Świerkowa tabliczka": "sprucesign",
"Brzozowa tabliczka": "birchsign",
"Tropikalna tabliczka": "junglesign",
"Akacjowa tabliczka": "acaciasign",
"Ciemnodębowa tabliczka": "darkoaksign",
"Szkarłatna tabliczka": "crimsonsign",
"Spaczona tabliczka": "warpedsign",
"Wiadro wody": "waterbucket",
"Wiadro lawy": "lavabucket",
"Wiadro sypkiego śniegu": "powdersnowbucket",
	"Śnieżka": "snowball",
"Skóra": "leather",
"Wiadro z mlekiem": "milkbucket",
"Wiadro z rozdymką": "pufferfishbucket",
"Wiadro z łososiem": "salmonbucket",
"Wiadro z dorszem": "codbucket",
"Wiadro z tropikalną rybą": "tropicalfishbucket",
"Wiadro z aksolotlem": "axolotlbucket",
"Cegła": "brick",
"Kulka gliny": "clayball",
"Blok suszonych wodorostów": "driedkelpblock",
"Papier": "paper",
"Książka": "book",
"Kula szlamu": "slimeball",
"Jajko": "egg",
"Kompas": "compass",
"Sakwa": "bundle",
"Wędka": "fishingrod",
"Zegar": "clock",
"Luneta": "spyglass",
"Jasnopył": "glowstonedust",
"Dorsz": "cod",
"Łosoś": "salmon",
"Ryba tropikalna": "tropicalfish",
"Rozdymka": "pufferfish",
"Pieczony dorsz": "cookedcod",
"Pieczony łosoś": "cookedsalmon",
"Torbiel z atramentem": "inksac",
"Torbiel ze świecącym atramentem": "glowinksac",
"Ziarna kakaowe": "cocoabeans",
"Biały barwnik": "whitedye",
"Pomarańczowy barwnik": "orangedye",
"Karmazynowy barwnik": "magentadye",
"Jasnoniebieski barwnik": "lightbluedye",
"Żółty barwnik": "yellowdye",
"Jasnozielony barwnik": "limedye",
"Różowy barwnik": "pinkdye",
"Szary barwnik": "graydye",
"Jasnoszary barwnik": "lightgraydye",
"Błękitny barwnik": "cyandye",
"Fioletowy barwnik": "purpledye",
"Niebieski barwnik": "bluedye",
"Brązowy barwnik": "browndye",
"Zielony barwnik": "greendye",
"Czerwony barwnik": "reddye",
"Czarny barwnik": "blackdye",
"Mączka kostna": "bonemeal",
"Kość": "bone",
"Cukier": "sugar",
"Ciasto": "cake",
"Białe łóżko": "whitebed",
"Pomarańczowe łóżko": "orangebed",
"Karmazynowe łóżko": "magentabed",
"Jasnoniebieskie łóżko": "lightbluebed",
"Żółte łóżko": "yellowbed",
"Jasnozielone łóżko": "limebed",
"Różowe łóżko": "pinkbed",
"Szare łóżko": "graybed",
"Jasnoszare łóżko": "lightgraybed",
"Błękitne łóżko": "cyanbed",
"Fioletowe łóżko": "purplebed",
"Niebieskie łóżko": "bluebed",
"Brązowe łóżko": "brownbed",
"Zielone łóżko": "greenbed",
"Czerwone łóżko": "redbed",
"Czarne łóżko": "blackbed",
"Ciastko": "cookie",
"Mapa eksploracyjna": "filledmap",
"Mapa": "filledmap",
"Nożyce": "shears",
"Kawałek arbuza": "melonslice",
"Suszony wodorost": "driedkelp",
"Nasiona dyni": "pumpkinseeds",
"Nasiona arbuza": "melonseeds",
"Surowa wołowina": "beef",
"Pieczona wołowina": "cookedbeef",
"Surowy kurczak": "chicken",
"Gotowany kurczak": "cookedchicken",
"Zgniłe mięso": "rottenflesh",
"Perła kresu": "enderpearl",
"Płomienna różdżka": "blazerod",
"łza Ghasta": "ghasttear",
"Bryłka złota": "goldnugget",
"Netherowa brodawka": "netherwart",
"Szklana butelka": "glassbottle",
"Oko pająka": "spidereye",
"Sfermentowane oko pająka": "fermentedspidereye",
"Płomienny proszek": "blazepowder",
"Krem magmowy": "magmacream",
"Statyw alchemiczny": "brewingstand",
"Kocioł": "cauldron",
"Oko Endera": "endereye",
"Kawałek lśniącego arbuza": "glisteringmelonslice",
"Jajo przyzywające aksolotla": "axolotlspawnegg",
"Jajo przyzywające nietoperza": "batspawnegg",
"Jajo przyzywające pszczołę": "beespawnegg",
"Jajo przyzywające płomyka": "blazespawnegg",
"Jajo przyzywające kota": "catspawnegg",
"Jajo przyzywające pająka jaskiniowego": "cavespiderspawnegg",
"Jajo przyzywające kurę": "chickenspawnegg",
"Jajo przyzywające dorsza": "codspawnegg",
"Jajo przyzywające krowę": "cowspawnegg",
"Jajo przyzywające creepera": "creeperspawnegg",
"Jajo przyzywające delfina": "dolphinspawnegg",
"Jajo przyzywające osła": "donkeyspawnegg",
"Jajo przyzywające utopca": "drownedspawnegg",
"Jajo przyzywające prastrażnika": "elderguardianspawnegg",
"Jajo przyzywające endermana": "endermanspawnegg",
"Jajo przyzywające endermita": "endermitespawnegg",
"Jajo przyzywające przywoływacza": "evokerspawnegg",
"Jajo przyzywające lisa": "foxspawnegg",
"Jajo przyzywające ghasta": "ghastspawnegg",
"Jajo przyzywające świecącą kałamarnicę": "glowsquidspawnegg",
"Jajo przyzywające kozę": "goatspawnegg",
"Jajo przyzywające strażnika": "guardianspawnegg",
"Jajo przyzywające hoglina": "hoglinspawnegg",
"Jajo przyzywające konia": "horsespawnegg",
"Jajo przyzywające posucha": "huskspawnegg",
"Jajo przyzywające lamę": "llamaspawnegg",
"Jajo przyzywające kostkę magmy": "magmacubespawnegg",
"Przywołaj: Mooshroom": "mooshroomspawnegg",
"Jajo przyzywające muła": "mulespawnegg",
	"Jajo przyzywające ocelota": "ocelotspawnegg",
"Jajo przyzywające pandę": "pandaspawnegg",
"Jajo przyzywające papugę": "parrotspawnegg",
"Jajo przyzywające fantoma": "phantomspawnegg",
"Jajo przyzywające świnię": "pigspawnegg",
"Jajo przyzywające piglina": "piglinspawnegg",
"Jajo przyzywające piglina okrutnika": "piglinbrutespawnegg",
"Jajo przyzywające rozbójnika": "pillagerspawnegg",
"Jajo przyzywające niedźwiedzia polarnego": "polarbearspawnegg",
"Jajo przyzywające rozdymkę": "pufferfishspawnegg",
"Jajo przyzywające królika": "rabbitspawnegg",
"Jajo przyzywające dewastatora": "ravagerspawnegg",
"Jajo przyzywające łososia": "salmonspawnegg",
"Jajo przyzywające owcę": "sheepspawnegg",
"Jajo przyzywające shulkera": "shulkerspawnegg",
"Jajo przyzywające rybika cukrowego": "silverfishspawnegg",
"Jajo przyzywające szkieleta": "skeletonspawnegg",
"Jajo przyzywające konia-szkieleta": "skeletonhorsespawnegg",
"Jajo przyzywające szlama": "slimespawnegg",
"Jajo przyzywające pająka": "spiderspawnegg",
"Jajo przyzywające kałamarnicę": "squidspawnegg",
"Jajo przyzywające tułacza": "strayspawnegg",
"Jajo przyzywające magmołaza": "striderspawnegg",
"Jajo przyzywające lamę handlarza": "traderllamaspawnegg",
"Przywołaj: Rybę tropikalną": "tropicalfishspawnegg",
"Jajo przyzywające żółwia": "turtlespawnegg",
"Jajo przyzywające dręczyciela": "vexspawnegg",
"Jajo przyzywające osadnika": "villagerspawnegg",
"Jajo przyzywające obrońcę": "vindicatorspawnegg",
"Jajo przyzywające wędrownego handlarza": "wanderingtraderspawnegg",
"Jajo przyzywające wiedźmę": "witchspawnegg",
"Jajo przyzywające witherowego szkieleta": "witherskeletonspawnegg",
"Jajo przyzywające wilka": "wolfspawnegg",
"Jajo przyzywające zoglina": "zoglinspawnegg",
"Jajo przyzywające zombie": "zombiespawnegg",
"Jajo przyzywające konia-zombie": "zombiehorsespawnegg",
"Jajo przyzywające osadnika-zombie": "zombievillagerspawnegg",
"Jajo przyzywające zzombifikowanego piglina": "zombifiedpiglinspawnegg",
"Ognista kula": "firecharge",
"Książka z piórem": "writablebook",
"Zapisana książka": "writtenbook",
"Ramka na przedmiot": "itemframe",
"Świecąca ramka na przedmiot": "glowitemframe",
"Doniczka": "flowerpot",
"Marchewka": "carrot",
"Ziemniak": "potato",
"Ugotowany ziemniak": "bakedpotato",
"Trujący ziemniak": "poisonouspotato",
"Pusta mapa": "map",
"Złota marchewka": "goldencarrot",
"Czaszka szkieleta": "skeletonskull",
"Czaszka witherowego szkieleta": "witherskeletonskull",
"Głowa gracza": "playerhead",
"Głowa zombie": "zombiehead",
"Głowa creepera": "creeperhead",
"Głowa smoka": "dragonhead",
"Netherowa gwiazda": "netherstar",
"Placek dyniowy": "pumpkinpie",
"Fajerwerka": "fireworkrocket",
"Gwiazdka pirotechniczna": "fireworkstar",
"Zaklęta książka": "enchantedbook",
"Netherowa cegła": "netherbrick",
"Odłamek pryzmarynu": "prismarineshard",
"Kryształy pryzmarynu": "prismarinecrystals",
"Surowy królik": "rabbit",
"Królicza łapka": "rabbit_foot",
"Pieczony królik": "cookedrabbit",
"Potrawka z królika": "rabbitstew",
"Królicza skóra": "rabbithide",
"Stojak na zbroje": "armorstand",
"Żelazna zbroja końska": "ironhorsearmor",
"Złota zbroja końska": "goldenhorsearmor",
"Diamentowa zbroja końska": "diamondhorsearmor",
"Skórzana zbroja końska": "leatherhorsearmor",
"Smycz": "lead",
"Znacznik": "nametag",
"Wagonik z blokiem poleceń": "commandblockminecart",
"Surowa baranina": "mutton",
"Pieczona baranina": "cookedmutton",
"Biały sztandar": "whitebanner",
"Pomarańczowy sztandar": "orangebanner",
"Karmazynowy sztandar": "magentabanner",
"Jasnoniebieski sztandar": "lightbluebanner",
"Żółty sztandar": "yellowbanner",
"Jasnozielony sztandar": "limebanner",
"Różowy sztandar": "pinkbanner",
"Szary sztandar": "graybanner",
"Jasnoszary sztandar": "lightgraybanner",
"Błękitny sztandar": "cyanbanner",
"Fioletowy sztandar": "purplebanner",
"Niebieski sztandar": "bluebanner",
"Brązowy sztandar": "brownbanner",
"Zielony sztandar": "greenbanner",
"Czerwony sztandar": "redbanner",
"Czarny sztandar": "blackbanner",
"Kryształ endu": "endcrystal",
"Owoc refrenusu": "chorusfruit",
"Prażony owoc refrenusu": "poppedchorusfruit",
"Burak": "beetroot",
"Nasiona buraka": "beetrootseeds",
"Barszcz czerwony": "beetrootsoup",
"Mikstura miotana": "splashpotion",
"Widmowa strzała": "spectralarrow",
"Strzała z miksturą": "tippedarrow",
"Trwała mikstura": "lingeringpotion",
"Tarcza": "shield",
"Totem nieśmiertelności villagera": "TOTEM VILLAGERA Z /RECEPTURA",
"Totem nieśmiertelności": "totemofundying",
"Skorupa shulkera": "shulkershell",
"Bryłka żelaza": "ironnugget",
"Księga wiedzy": "knowledgebook",
"Patyk debugujący": "debugstick",
"Płyta muzyczna 13": "musicdisc13",
"Płyta muzyczna Cat": "musicdisccat",
"Płyta muzyczna Blocks": "musicdiscblocks",
"Płyta muzyczna Chirp": "musicdiscchirp",
"Płyta muzyczna Far": "musicdiscfar",
"Płyta muzyczna Mall": "musicdiscmall",
"Płyta muzyczna Mellohi": "musicdiscmellohi",
"Płyta muzyczna Stal": "musicdiscstal",
"Płyta muzyczna Strad": "musicdiscstrad",
"Płyta muzyczna Ward": "musicdiscward",
"Płyta muzyczna 11": "musicdisc11",
"Płyta muzyczna Wait": "musicdiscwait",
"Płyta muzyczna Pigstep": "musicdiscpigstep",
"Trójząb": "trident",
"Błona fantoma": "phantommembrane",
"Muszla łodzika": "nautilusshell",
"Serce oceanu": "heartofthesea",
"Kusza": "crossbow",
"Podejrzana potrawka": "suspiciousstew",
"Krosno": "loom",
"Wzór sztandaru z kwiatem": "flowerbannerpattern",
"Wzór sztandaru z creeperem": "creeperbannerpattern",
"Wzór sztandaru ze szkieletem": "skullbannerpattern",
"Wzór sztandaru Mojang": "mojangbannerpattern",
"Wzór sztandaru globu": "globebannerpattern",
"Wzór sztandaru piglina": "piglinbannerpattern",
"Kompostownik": "composter",
"Beczka": "barrel",
"Wędzarka": "smoker",
"Piec hutniczy": "blastfurnace",
"Stół kartograficzny": "cartographytable",
"Stół łuczarski": "fletchingtable",
"Kamień szlifierski": "grindstone",
"Stół kowalski": "smithingtable",
"Przecinarka": "stonecutter",
"Dzwon": "bell",
"Latarenka": "lantern",
"Eteryczna latarenka": "soullantern",
"Świecące jagody": "glowberries",
"Ognisko": "campfire",
"Eteryczne ognisko": "soulcampfire",
"Światłogrzyb": "shroomlight",
"Plaster miodu": "honeycomb",
"Gniazdo pszczół": "beenest",
"Ul": "beehive",
"Butelka miodu": "honeybottle",
"Blok plastra miodu": "honeycombblock",
"Magnetyt": "lodestone",
"Płaczący obsydian": "cryingobsidian",
"Czernit": "blackstone",
"Czernitowa płyta": "blackstoneslab",
"Czernitowe schody": "blackstonestairs",
"Złocony czernit": "gildedblackstone",
"Wypolerowany czernit": "polishedblackstone",
"Wypolerowana czernitowa płyta": "polishedblackstoneslab",
"Wypolerowane czernitowe schody": "polishedblackstonestairs",
"Rzeźbiony wypolerowany czernit": "chiseledpolishedblackstone",
"Wypolerowane czernitowe cegły": "polishedblackstonebricks",
"Wypolerowana czernitowa ceglana płyta": "polishedblackstonebrickslab",
"Wypolerowane czernitowe ceglane schody": "polishedblackstonebrickstairs",
"Popękane wypolerowane czernitowe cegły": "crackedpolishedblackstonebricks",
"Kotwica odrodzenia": "respawnanchor",
"Świeca": "candle",
"Biała świeca": "whitecandle",
"Pomarańczowa świeca": "orangecandle",
"Karmazynowa świeca": "magentacandle",
"Jasnoniebieska świeca": "lightbluecandle",
"Żółta świeca": "yellowcandle",
"Jasnozielona świeca": "limecandle",
"Różowa świeca": "pinkcandle",
"Szara świeca": "graycandle",
"Jasnoszara świeca": "lightgraycandle",
"Błękitna świeca": "cyancandle",
"Fioletowa świeca": "purplecandle",
"Niebieska świeca": "bluecandle",
"Brązowa świeca": "browncandle",
"Zielona świeca": "greencandle",
"Czerwona świeca": "redcandle",
"Czarna świeca": "blackcandle",
"Mały zarodek ametystu": "smallamethystbud",
"Średni zarodek ametystu": "mediumamethystbud",
"Duży zarodek ametystu": "largeamethystbud",
"Skupisko ametystu": "amethystcluster",
"Spiczasty naciek": "pointeddripstone",
"Powietrze": "air",
"Woda": "water",
"Lawa": "lava",
"Wysoka trawa morska": "tallseagrass",
"Głowica tłoka": "pistonhead",
"Poruszany blok": "movingpiston",
"Ścienna pochodnia": "walltorch",
"Ogień": "fire",
"Eteryczny ogień": "soulfire",
"Przewód redstone": "redstonewire",
"Dębowa ścienna tabliczka": "oakwallsign",
"Świerkowa ścienna tabliczka": "sprucewallsign",
"Brzozowa ścienna tabliczka": "birchwallsign",
"Akacjowa ścienna tabliczka": "acaciawallsign",
"Tropikalna ścienna tabliczka": "junglewallsign",
"Ciemnodębowa ścienna tabliczka": "darkoakwallsign",
"Ścienna pochodnia redstone": "redstonewalltorch",
"Ścienna eteryczna pochodnia": "soulwalltorch",
"Netherowy portal": "netherportal",
"Przyłączona łodyga dyni": "attachedpumpkinstem",
"Przyłączona łodyga arbuza": "attachedmelonstem",
"Łodyga dyni": "pumpkinstem",
"Łodyga arbuza": "melonstem",
"Kocioł wody": "watercauldron",
"Kocioł lawy": "lavacauldron",
"Kocioł sypkiego śniegu": "powdersnowcauldron",
"Portal do Endu": "endportal",
"Kakao": "cocoa",
"Linka": "tripwire",
"Sadzonka dębu w doniczce": "pottedoaksapling",
"Sadzonka świerku w doniczce": "pottedsprucesapling",
"Sadzonka brzozy w doniczce": "pottedbirchsapling",
"Sadzonka tropikalna w doniczce": "pottedjunglesapling",
"Sadzonka akacji w doniczce": "pottedacaciasapling",
"Sadzonka ciemnego dębu w doniczce": "potteddarkoaksapling",
"Paproć w doniczce": "pottedfern",
"Mlecz w doniczce": "potteddandelion",
"Mak w doniczce": "pottedpoppy",
"Niebieska orchidea w doniczce": "pottedblueorchid",
"Czosnek w doniczce": "pottedallium",
"Houstonia błękitna w doniczce": "pottedazurebluet",
"Czerwony tulipan w doniczce": "pottedredtulip",
"Pomarańczowy tulipan w doniczce": "pottedorangetulip",
"Biały tulipan w doniczce": "pottedwhitetulip",
"Różowy tulipan w doniczce": "pottedpinktulip",
"Margaretka w doniczce": "pottedoxeyedaisy",
"Chaber w doniczce": "pottedcornflower",
"Konwalia w doniczce": "pottedlilyofthevalley",
"Witherowa róża w doniczce": "pottedwitherrose",
"Muchomor w doniczce": "pottedredmushroom",
"Borowik w doniczce": "pottedbrownmushroom",
"Uschnięty krzak w doniczce": "potteddeadbush",
"Kaktus w doniczce": "pottedcactus",
"Marchewki": "carrots",
"Ziemniaki": "potatoes",
"Ścienna czaszka szkieleta": "skeletonwallskull",
"Ścienna czaszka witherowego szkieleta": "witherskeletonwallskull",
"Ścienna głowa zombie": "zombiewallhead",
"Ścienna głowa gracza": "playerwallhead",
"Ścienna głowa creepera": "creeperwallhead",
"Ścienna głowa smoka": "dragonwallhead",
"Buraki": "beetroots",
"Brama Endu": "endgateway",
"Oszroniony lód": "frostedice",
"Rosnące wodorosty": "kelpplant",
"Martwy wachlarz naścienny koralowca rurkowatego": "deadtubecoralwallfan",
"Martwy wachlarz naścienny koralowca mózgowatego": "deadbraincoralwallfan",
"Martwy wachlarz naścienny koralowca bąbelkowatego": "deadbubblecoralwallfan",
"Martwy wachlarz naścienny koralowca ognistego": "deadfirecoralwallfan",
"Martwy wachlarz naścienny koralowca rogatego": "deadhorncoralwallfan",
"Wachlarz naścienny koralowca rurkowatego": "tubecoralwallfan",
"Wachlarz naścienny koralowca mózgowatego": "braincoralwallfan",
"Wachlarz naścienny koralowca bąbelkowatego": "bubblecoralwallfan",
"Wachlarz naścienny koralowca ognistego": "firecoralwallfan",
"Wachlarz naścienny koralowca rogatego": "horncoralwallfan",
"Pęd bambusa": "bamboo",
"Bambus w doniczce": "pottedbamboo",
"Próżniowe powietrze": "voidair",
"Powietrze jaskiniowe": "caveair",
"Kolumna bąbelków": "bubblecolumn",
"Słodkie jagody": "sweet_berries",
"Krzew słodkich jagód": "sweetberrybush",
"Rosnąca lamentorośl": "weepingvinesplant",
"Rosnąca krętorośl": "twistingvinesplant",
"Szkarłatna ścienna tabliczka": "crimsonwallsign",
"Spaczona ścienna tabliczka": "warpedwallsign",
"Szkarłatny grzyb w doniczce": "pottedcrimsonfungus",
"Spaczony grzyb w doniczce": "pottedwarpedfungus",
"Szkarłatne korzenie w doniczce": "pottedcrimsonroots",
"Spaczone korzenie w doniczce": "pottedwarpedroots",
"Ciasto ze świeczką": "candlecake",
"Ciasto z białą świeczką": "whitecandlecake",
"Ciasto z pomarańczową świeczką": "orangecandlecake",
"Ciasto z karmazynową świeczką": "magentacandlecake",
"Ciasto z jasnoniebieską świeczką": "lightbluecandlecake",
"Ciasto z żółtą świeczką": "yellowcandlecake",
"Ciasto z jasnozieloną świeczką": "limecandlecake",
"Ciasto z różową świeczką": "pinkcandlecake",
"Ciasto z szarą świeczką": "graycandlecake",
"Ciasto z jasnoszarą świeczką": "lightgraycandlecake",
"Ciasto z błękitną świeczką": "cyancandlecake",
"Ciasto z fioletową świeczką": "purplecandlecake",
"Ciasto z niebieską świeczką": "bluecandlecake",
"Ciasto z brązową świeczką": "browncandlecake",
"Ciasto z zieloną świeczką": "greencandlecake",
"Ciasto z czerwoną świeczką": "redcandlecake",
"Ciasto z czarną świeczką": "blackcandlecake",
"Sypki śnieg": "powdersnow",
"Jaskiniowe pnącza": "cavevines",
"Rosnące jaskiniowe pnącza": "cavevinesplant",
"Łodyga wielkiego spadkoliścia": "bigdripleafstem",
"Azalia w doniczce": "pottedazaleabush",
"Kwitnąca azalia w doniczce": "pottedfloweringazaleabush",
"Butelka": "glassbottle",
"Pieczony schab": "cookedporkchop",
"Befsztyk": "cookedbeef",
"Wiaderko": "bucket",
"Sadzonka wiśni": "cherrysapling",




"Szablon kowalski: Zdobienie zbroi - Wartownik": "sentry_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Dręczyciel": "vex_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Dzicz": "wild_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Wybrzeże": "coast_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Wydma": "dune_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Drogowskaz": "wayfinder_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Hodowca": "raiser_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Rzeźbiarz": "shaper_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Gospodarz": "host_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Nadzorca": "ward_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Cisza": "silence_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Fala": "tide_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Ryjek": "snout_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Żebra": "rib_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Oko": "eye_armor_trim_smithing_template",
"Szablon kowalski: Zdobienie zbroi - Iglica": "spire_armor_trim_smithing_template",


        };

        document.addEventListener('DOMContentLoaded', function () {
            const generateButton = document.getElementById('generateButton');
            generateButton.addEventListener('click', extractItems);

            const resultsDiv = document.getElementById('results');

            resultsDiv.addEventListener('click', function (event) {
                if (event.target.classList.contains('copy')) {
                    const copyButton = event.target;

                    copyButton.classList.add('clicked');

                    const textArea = document.createElement('textarea');
                    textArea.value = copyButton.previousSibling.textContent;
                    document.body.appendChild(textArea);
                    textArea.select();
                    document.execCommand('copy');
                    document.body.removeChild(textArea);

                    const commandDiv = copyButton.parentElement;
                    commandDiv.classList.add('copied');

                    resultsDiv.querySelectorAll('.commandDiv').forEach(result => {
                        if (result !== commandDiv) {
                            result.classList.remove('copied');
                        }
                    });
                }
            });
        });

        function translateWords(dictionary, text) {
            for (const [key, value] of Object.entries(dictionary)) {
                const regex = new RegExp(`(?:^|[^\\p{L}])${escapeRegExp(key)}(?:$|[^\\p{L}])`, 'gu');
                text = text.replace(regex, value);
            }
            return text;
        }

        function escapeRegExp(string) {
            return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        }

        function reset() {
            currentCommandIndex = 0;
        }

        function extractItems() {
            reset();
            const message = document.getElementById('message').value;

            const pattern = /\[([^\[\]]+?)(?:\s(\d{1,2})%?)?(?:\s(?:x(\d)|Ench:(.*?)))?\]/gu;
            const items = message.matchAll(pattern);

            const results = document.getElementById('results');
            results.textContent = '';

            for (const item of items) {
                let [_, name, percent, quantity, enchantments] = item;

                if (percent) {
                    name = name.replace(/\s\d{1,2}%?\s?$/, '').trim();
                }

                const itemCount = quantity ? parseInt(quantity, 10) : 1;
                const enchantmentsText = enchantments ? enchantments.trim() : '';

                let command;
                if (name.includes('x')) {
                    const [itemName, itemQuantity] = name.split('x');
                    command = `/i  ${itemName.trim()}  ${itemQuantity}${formatEnchantments(enchantmentsText)}`;
                } else {
                    const itemNameWithoutQuotes = name.replace(/Nazw\. dodatk: ".*?"/g, '').trim();
                    const itemNameWithoutSpaces = itemNameWithoutQuotes.replace(/(\S)\s*{/g, '$1{');
                    command = `/i  ${itemNameWithoutSpaces}  ${itemCount}${formatEnchantments(enchantmentsText)}`;
                }

                command = command.replace(/\s\d{1,2}%\s?/g, ' ');
                command = command.replace(/\sx\d+/g, '');
                command = translateWords(dictionary, command);

                const copyButton = document.createElement('button');
                copyButton.textContent = 'Kopiuj';
                copyButton.classList.add('copy');
                copyButton.addEventListener('click', function () {
                    copyToClipboard(command);
                });

                const commandDiv = document.createElement('div');
                commandDiv.textContent = command;
                commandDiv.classList.add('commandDiv');
                commandDiv.appendChild(copyButton);

                results.appendChild(commandDiv);
            }
        }

        function formatEnchantments(enchantmentsText) {
            if (!enchantmentsText) return '';
            const enchantmentList = enchantmentsText.split(", ");
            const enchantmentCommands = enchantmentList.map(ench => {
                const [id, lvl] = ench.split("-");
                return `{id:"${id}",lvl:${lvl}}`;
            });
            return ` {Enchantments:[${enchantmentCommands.join(',')}]}`;
        }

        function copyToClipboard(text) {
            const textArea = document.createElement('textarea');
            textArea.value = text;
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand('copy');
            document.body.removeChild(textArea);
        }
